services:
  - type: web
    name: tv-remote-control
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tv-remote-db
          property: connectionString

databases:
  - name: tv-remote-db
    plan: free
    databaseName: tv_remote_control
    user: tv_remote_user